#!/bin/bash
# chkconfig: 2345 20 80
# description: LolliBird Server

# Source function library.
. /etc/init.d/functions

start() {
    # code to start app comes here 
    /usr/share/nginx/server/Godot_server_v3.2.3 --main-pack /usr/share/nginx/server/server.pck &
}

stop() {
    # code to stop app comes here 
    killproc Godot_server_v3.2.3
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status Godot_server_v3.2.3
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
